const API_BASE='https://win-pro-com-ecyg.onrender.com';
const $=id=>document.getElementById(id);let accessToken=localStorage.getItem('winbd_access')||'';let refreshToken=localStorage.getItem('winbd_refresh')||'';
const GAMES=[['JILI','JILI Games','🎰'],['Super Ace','Super Ace','🃏'],['Aviator','Aviator','✈️'],['Slots','Slot Games','🎰'],['Live Casino','Live Casino','🎥'],['Sports','Sports','⚽'],['Fishing','Fishing Games','🎣'],['Arcade','Arcade Games','🕹️'],['Crash','Crash Games','💥'],['Table Games','Table Games','🎲']];
function apiUrl(path){return `${API_BASE}${path}`;}async function api(url,opts={}){const headers={'Content-Type':'application/json',...(opts.headers||{})};if(accessToken)headers.Authorization=`Bearer ${accessToken}`;let r=await fetch(apiUrl(url),{...opts,headers});if(r.status===401&&refreshToken){const rr=await fetch(apiUrl('/api/bt/v1/user/refreshToken'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refreshToken})});const rd=await rr.json();if(rr.ok){accessToken=rd.data.accessToken;refreshToken=rd.data.refreshToken;localStorage.setItem('winbd_access',accessToken);localStorage.setItem('winbd_refresh',refreshToken);headers.Authorization=`Bearer ${accessToken}`;r=await fetch(apiUrl(url),{...opts,headers});}}return r;}
async function health(){try{const r=await fetch(apiUrl('/api/bt/health'),{cache:'no-store'});const d=await r.json();const el=$('health');if(el)el.textContent=d.status==='000000'?'Connected':'Unavailable';}catch{const el=$('health');if(el)el.textContent='Unavailable';}}
function show(id){document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==id);if(id==='games')renderGames();if(id==='wallet'){loadWallet();loadHistory();}if(id==='profile')loadProfile();if(id==='history')loadHistory();if(id==='home')health();window.scrollTo({top:0,behavior:'smooth'});}
function renderGames(){const grid=$('gameGrid');if(!grid)return;const q=($('gameSearch')?.value||'').toLowerCase();const f=$('gameFilter')?.value||'all';const list=GAMES.filter(([provider,name])=>(f==='all'||provider===f)&&(`${provider} ${name}`).toLowerCase().includes(q));grid.innerHTML=list.map(([provider,name,icon])=>`<article class="game-tile"><div class="tile-art game-provider">${icon}</div><span class="provider-label">${provider}</span><h3>${name}</h3><p>Provider integration pending</p><button class="primary" onclick="launchGame('${provider}')">Launch</button></article>`).join('')||'<div class="card"><h3>কোনো গেম পাওয়া যায়নি</h3><p>Search/filter পরিবর্তন করে আবার চেষ্টা করুন।</p></div>';}
function launchGame(provider){toast(`${provider} launch API এখনো যুক্ত করা হয়নি`);}
function openModal(type){const register=type==='register';$('modalBody').innerHTML=`<h2>${register?'অ্যাকাউন্ট তৈরি করুন':'লগইন'}</h2><form onsubmit="${register?'register(event)':'login(event)'}">${register?'<input id="fullName" placeholder="পুরো নাম"><input id="email" type="email" placeholder="ইমেইল">':''}<input id="username" placeholder="ইউজারনেম" required><input id="password" type="password" placeholder="পাসওয়ার্ড" minlength="8" required>${register?'<input id="phone" placeholder="ফোন নম্বর"><input id="confirm" type="password" placeholder="পাসওয়ার্ড নিশ্চিত করুন" minlength="8" required>':''}<button class="primary">${register?'রেজিস্টার':'লগইন'}</button><div id="formMsg"></div></form>`;$('modal').hidden=false;}
function closeModal(){$('modal').hidden=true;}async function login(e){e.preventDefault();try{const r=await api('/api/bt/v2_1/user/login',{method:'POST',body:JSON.stringify({username:$('username').value,password:$('password').value})});const d=await r.json();if(!r.ok){$('formMsg').className='msg';$('formMsg').textContent=d.message||'লগইন ব্যর্থ হয়েছে';return;}setTokens(d.data);closeModal();updateNav();show('profile');toast('লগইন সফল হয়েছে');}catch{$('formMsg').className='msg';$('formMsg').textContent='Backend-এ সংযোগ করা যাচ্ছে না';}}
async function register(e){e.preventDefault();if($('password').value!==$('confirm').value){$('formMsg').className='msg';$('formMsg').textContent='পাসওয়ার্ড মিলছে না';return;}try{const body={username:$('username').value,password:$('password').value,fullName:$('fullName').value||undefined,email:$('email').value||undefined,phone:$('phone').value||undefined};const r=await api('/api/bt/v2_1/user/register',{method:'POST',body:JSON.stringify(body)});const d=await r.json();if(!r.ok){$('formMsg').className='msg';$('formMsg').textContent=d.message||'রেজিস্ট্রেশন ব্যর্থ হয়েছে';return;}setTokens(d.data);closeModal();updateNav();show('profile');toast('অ্যাকাউন্ট তৈরি হয়েছে');}catch{$('formMsg').className='msg';$('formMsg').textContent='Backend-এ সংযোগ করা যাচ্ছে না';}}
function setTokens(d){accessToken=d.accessToken;refreshToken=d.refreshToken;localStorage.setItem('winbd_access',accessToken);localStorage.setItem('winbd_refresh',refreshToken);}async function logout(){try{await api('/api/bt/v1/user/logout',{method:'POST',body:JSON.stringify({refreshToken})});}catch{}accessToken='';refreshToken='';localStorage.removeItem('winbd_access');localStorage.removeItem('winbd_refresh');updateNav();show('home');toast('লগআউট হয়েছে');}function updateNav(){const logout=$('logout'),loginBtn=$('loginBtn'),registerBtn=$('registerBtn');if(logout)logout.hidden=!accessToken;if(loginBtn)loginBtn.hidden=!!accessToken;if(registerBtn)registerBtn.hidden=!!accessToken;}
async function loadWallet(){const el=$('walletData');if(!el)return;if(!accessToken){el.innerHTML='<p>ওয়ালেট দেখতে আগে লগইন করুন।</p>';return}try{const r=await api('/api/bt/v1/user/getBalance');const d=await r.json();if(!r.ok){el.textContent=d.message;return}el.innerHTML=`<div class="cards"><div class="card"><span>উপলভ্য</span><b>৳ ${Number(d.data.balance).toLocaleString()}</b></div><div class="card"><span>লকড</span><b>৳ ${Number(d.data.locked_balance).toLocaleString()}</b></div></div>`;}catch{el.textContent='ওয়ালেট তথ্য পাওয়া যাচ্ছে না';}}
async function loadProfile(){const el=$('profileData');if(!el)return;if(!accessToken){el.textContent='প্রোফাইল দেখতে আগে লগইন করুন।';return}try{const r=await api('/api/bt/v1/user/getProfile');const d=await r.json();if(!r.ok){el.textContent=d.message;return}const u=d.data;el.innerHTML=`<p><b>ইউজারনেম:</b> ${u.username}</p><p><b>নাম:</b> ${u.fullName||'—'}</p><p><b>ইমেইল:</b> ${u.email||'—'}</p><p><b>ফোন:</b> ${u.phone||'—'}</p><p><b>কারেন্সি:</b> ${u.currency||'BDT'}</p><p><b>স্ট্যাটাস:</b> ${u.status}</p>`;}catch{el.textContent='প্রোফাইল তথ্য পাওয়া যাচ্ছে না';}}
async function saveProfile(e){e.preventDefault();const r=await api('/api/bt/v1/user/saveProfile',{method:'POST',body:JSON.stringify({fullName:$('editName').value,email:$('editEmail').value,phone:$('editPhone').value})});const d=await r.json();toast(r.ok?'প্রোফাইল আপডেট হয়েছে':(d.message||'আপডেট ব্যর্থ'));if(r.ok)loadProfile();}async function changePassword(e){e.preventDefault();const r=await api('/api/bt/v1/user/changePassword',{method:'POST',body:JSON.stringify({oldPassword:$('oldPass').value,newPassword:$('newPass').value})});const d=await r.json();toast(r.ok?'পাসওয়ার্ড পরিবর্তন হয়েছে':(d.message||'পাসওয়ার্ড পরিবর্তন ব্যর্থ'));if(r.ok)e.target.reset();}
async function loadHistory(){const el=$('historyData');if(!el)return;if(!accessToken){el.textContent='হিস্টোরি দেখতে আগে লগইন করুন।';return}try{const r=await api('/api/bt/v1/payment/history');const d=await r.json();if(!r.ok){el.textContent=d.message||'হিস্টোরি পাওয়া যাচ্ছে না';return}el.innerHTML=d.data.length?d.data.map(x=>`<div class="history-row"><b>${x.direction==='deposit'?'ডিপোজিট':'উইথড্র'}</b><span>৳ ${Number(x.amount).toLocaleString()}</span><span>${x.method}</span><span>${x.status}</span></div>`).join(''):'<p>এখনও কোনো transaction নেই।</p>';}catch{el.textContent='হিস্টোরি পাওয়া যাচ্ছে না';}}
async function payment(e,direction){e.preventDefault();if(!accessToken){toast('লগইন প্রয়োজন');return}const amount=Number($(direction==='deposit'?'depAmount':'wdAmount').value),method=$(direction==='deposit'?'depMethod':'wdMethod').value;const r=await api(`/api/bt/v1/payment/${direction}`,{method:'POST',body:JSON.stringify({amount,method})});const d=await r.json();if(!r.ok){toast(d.message||'রিকোয়েস্ট ব্যর্থ হয়েছে');return;}e.target.reset();if(direction==='deposit'&&d.data?.nextAction?.url){toast('SSLCOMMERZ Sandbox checkout খোলা হচ্ছে…');window.location.href=d.data.nextAction.url;return;}toast('পেমেন্ট রিকোয়েস্ট তৈরি হয়েছে');loadWallet();loadHistory();}
function handlePaymentResult(){const p=new URLSearchParams(location.search).get('payment');if(p==='success')toast('Sandbox payment সফল হয়েছে');else if(p==='failed')toast('Sandbox payment ব্যর্থ হয়েছে');}
function toast(t){const x=$('toast');if(!x)return;x.textContent=t;x.style.cssText='position:fixed;bottom:22px;right:22px;padding:12px 16px;background:#132238;border:1px solid #31506f;border-radius:10px;z-index:40';setTimeout(()=>x.textContent='',2200)}health();updateNav();renderGames();handlePaymentResult();